server.port=8080
spring.application.name=java-frontend

python.backend.url=http://localhost:8000

logging.level.com.elastic.workshop=INFO
logging.level.org.springframework.web.client=WARN

spring.thymeleaf.cache=false
